### ISSUE TITLE
Django version 3.2 does not support hyphens in app label

### ISSUE THREAD

**Issue by ppremkumar** [ezrajrice/django-advanced_password_validation#3]
Hi. It looks like Django version 3.2 does not support hyphens in INSTALLED_APPS or anywhere within settings.py.
After upgrading to Django 3.2, I get the below error:
django.core.exceptions.improperlyconfigured: the app label 'django-advanced_password_validation' is not a valid python identifier

Therefore, inside the "site-packages" folder in my virtual environment, I had to rename "django-advanced_password_validation" to "django_advanced_password_validation"

![image](https://user-images.githubusercontent.com/6050216/120881917-1c26e280-c5f2-11eb-891f-c507b6ab6eaf.png)

Also, within settings.py, I had to replace every occurrence of 'django-advanced_password_validation' to 'django_advanced_password_validation.'

**Comment by GorlikItsMe** [comment]
Hi
I have simillar problem.
in settings.py before INSTALLED_APPS add
```
sys.modules['django_advanced_password_validation'] = __import__('django-advanced_password_validation')
```

and use `django_advanced_password_validation` for `INSTALLED_APPS`

Solution from here
https://github.com/FortAwesome/Font-Awesome/issues/17801#issuecomment-844291432

**Comment by ezrajrice** [comment]
Sorry this took so long to fix. Life got in the way and this got buried in other notifications.
